name: Test and Share Artifacts

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--ignore-scripts]

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Test
        run: |
          pnpm test

  share-artifacts:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Save tag name
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: echo "${GITHUB_REF/refs\/tags\//}" > tag_name.txt

      - name: Upload tag name
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: tag_name
          path: tag_name.txt
